Repository sunspec/pysunspec, pull requests merged in 2020-01, with the labels that each got.

#63 Close files in PathList.read() to avoid resource warnings
  sunspec/core/util.py
Labels: enhancement

#64 Avoid collisions between matching symbol IDs for different points
  sunspec/core/device.py
  sunspec/core/test/test_device.py
Labels: enhancement

#68 Drop support for Python 3.3 and 3.4
  .travis.yml
  README.md
  doc/pysunspec.rst
  sunspec/core/client.py
  sunspec/core/data.py
  sunspec/core/device.py
  sunspec/core/modbus/client.py
  sunspec/core/modbus/mbmap.py
  sunspec/core/test/test_all.py
  sunspec/core/test/test_client.py
  sunspec/core/test/test_data.py
  sunspec/core/test/test_device.py
  sunspec/core/test/test_util.py
  sunspec/core/util.py
Labels: version support

#69 spellcheck corrections and added some tips for installation
  README.md
Labels: typos

#77 Fix typo in Point.__str__
  sunspec/core/device.py
Labels: typos

#79 changed load()'s call to point_class to be keyworded
  sunspec/core/device.py
Labels: enhancement

#72 Correct point assignment scaling and rounding
  sunspec/core/device.py
  sunspec/core/test/test_device.py
Labels: enhancement
